[package]
name = "dora-cli"
version.workspace = true
edition = "2021"
documentation.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dora"
path = "src/main.rs"

[features]
default = ["tracing"]
tracing = ["dep:dora-tracing"]

[dependencies]
clap = { version = "4.0.3", features = ["derive"] }
eyre = "0.6.8"
dora-core = { workspace = true }
dora-node-api-c = { workspace = true }
dora-operator-api-c = { workspace = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.9.11"
webbrowser = "0.8.3"
serde_json = "1.0.86"
termcolor = "1.1.3"
uuid = { version = "1.7", features = ["v7", "serde"] }
inquire = "0.5.2"
communication-layer-request-reply = { workspace = true }
notify = "5.1.0"
ctrlc = "3.2.5"
tracing = "0.1.36"
dora-tracing = { workspace = true, optional = true }
bat = "0.24.0"
dora-daemon = { workspace = true }
dora-coordinator = { workspace = true }
dora-runtime = { workspace = true }
tokio = { version = "1.20.1", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["io-util", "net"] }
futures = "0.3.21"
duration-str = "0.5"
